{% set version = "1.64.0" %}
{% set filename = "boost_%s.tar.bz2" % version.replace(".", "_") %}

package:
  name: boost
  version: {{ version }}

source:
  fn:  {{ filename }}
  url: https://dl.bintray.com/boostorg/release/{{ version }}/source/{{ filename }}
  sha256: 7bcc5caace97baa948931d712ea5f37038dbb1c5d89b43ad4def4ed7cb683332
  patches:
    # Applies a patch to correct `BOOST_LIB_NAME` on Python 3.
    #
    # xref: https://github.com/boostorg/python/pull/135
    #
    - PR_135.diff

build:
  number: 5
  features:
    - vc{{ vc }}   # [win]
  run_exports:
    # Keep boost pinned to minor version
    - {{ pin_subpackage('boost', max_pin='x.x') }}

requirements:
  build:
    - python
    - numpy
    - boost-cpp {{ version }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  run:
    - python
    - numpy
    # boost-cpp removed here because package has run_exports for itself
    #    https://github.com/AnacondaRecipes/boost-cpp-feedstock/pull/1
    # this req isn't actually necessary, as run_exports will add it.  Left here for reference.
    # - boost-cpp {{ version }}

test:
  commands:
    # Verify Python headers are installed.
    - test -f $PREFIX/include/boost/python.hpp                 # [unix]
    - test -d $PREFIX/include/boost/python                     # [unix]
    - if not exist %LIBRARY_INC%\\boost\\python.hpp exit 1     # [win]
    - if not exist %LIBRARY_INC%\\boost\\python exit 1         # [win]

    # Verify libraries.
    {% set win_vstr = "_".join(version.split(".")[:2]) %}
    {% set py3k_suffix = "3" if py3k else "" %}
    {% set boost_libs = [
            "python%s" % py3k_suffix,
            "numpy%s" % py3k_suffix
    ] %}
    {% for each_boost_lib in boost_libs %}
    - test -f $PREFIX/lib/libboost_{{ each_boost_lib }}.a                                                 # [unix]
    - test -f $PREFIX/lib/libboost_{{ each_boost_lib }}.dylib                                             # [osx]
    - test -f $PREFIX/lib/libboost_{{ each_boost_lib }}.so                                                # [linux]
    - if not exist %PREFIX%\\Library\\bin\\boost_{{ each_boost_lib }}-vc90-mt-{{ win_vstr }}.dll exit 1   # [win and vc==9]
    - if not exist %PREFIX%\\Library\\bin\\boost_{{ each_boost_lib }}-vc100-mt-{{ win_vstr }}.dll exit 1  # [win and vc==10]
    - if not exist %PREFIX%\\Library\\bin\\boost_{{ each_boost_lib }}-vc140-mt-{{ win_vstr }}.dll exit 1  # [win and vc==14]
    - if not exist %PREFIX%\\Library\\lib\\boost_{{ each_boost_lib }}-vc90-mt-{{ win_vstr }}.lib exit 1   # [win and vc==9]
    - if not exist %PREFIX%\\Library\\lib\\boost_{{ each_boost_lib }}-vc100-mt-{{ win_vstr }}.lib exit 1   # [win and vc==10]
    - if not exist %PREFIX%\\Library\\lib\\boost_{{ each_boost_lib }}-vc140-mt-{{ win_vstr }}.lib exit 1  # [win and vc==14]
    {% endfor %}
    - conda inspect linkages -p $PREFIX boost  # [not win]
    - conda inspect objects -p $PREFIX boost  # [osx]

about:
  home: http://www.boost.org/
  license: Boost-1.0
  summary: Free peer-reviewed portable C++ source libraries.

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - msarahan
    - ocefpaf
    - jschueller
    - scopatz
    - isuruf
